# Email Spam Prediction using logistic regression

**Import all the necessary libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Import Dataset**

In [ ]:
email = pd.read_csv('/content/emails.csv')

In [ ]:
email.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [ ]:
from sklearn.model_selection import train_test_split

**Train - Test Split**

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(email.drop('spam',axis=1),
                                                    email['spam'], test_size=0.30,
                                                    random_state=101)

# **SVM Classification**

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_classifier=SVC(kernel='linear')
svc_classifier.fit(X_train,y_train)


SVC(kernel='linear')

In [ ]:
predictions=svc_classifier.predict(x_test)


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)


[[1066    2    1    0]
 [   3   11    0    0]
 [   1    0    0    0]
 [   1    1    0    0]]


0.9917127071823204

# **KNN Classification**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train,y_train)


KNeighborsClassifier()

In [ ]:
pred = knn.predict(x_test)


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix


In [ ]:
print(confusion_matrix(y_test,pred))


[[1068    1    0    0]
 [  13    1    0    0]
 [   1    0    0    0]
 [   2    0    0    0]]


In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,pred)
print(f'Accuracy: {round(score*100,2)}%')


Accuracy: 98.43%


# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Assuming you have already imported necessary libraries and loaded your data

# 1. Data Preprocessing
label_encoder = LabelEncoder()
x_train['Email No.'] = label_encoder.fit_transform(x_train['Email No.'])

x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.3, random_state=42)




**Logistic Regression Model**

In [ ]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
spam = logmodel.predict(x_test)

**Accuracy score**

In [ ]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,spam)
score

0.9917127071823204

In [47]:
%%shell
jupyter nbconvert --to html /content/Email_Spam_Prediction_Logistic_Reg,SVM,KNN___RA2111_148.ipynb

[NbConvertApp] Converting notebook /content/Email_Spam_Prediction_Logistic_Reg,SVM,KNN___RA2111_148.ipynb to html
[NbConvertApp] Writing 631005 bytes to /content/Email_Spam_Prediction_Logistic_Reg,SVM,KNN___RA2111_148.html
